name: thegorgeousotp
description: The Gorgeous OTP

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^1.0.1
  contacts_service: ^0.4.6
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  flutter_mobx: ^1.1.0
  font_awesome_flutter: ^9.0.0
  google_fonts: ^2.0.0
  image_cropper: ^1.4.0
  image_picker: ^0.7.2+1
  mobx: ^1.1.1
  numeric_keyboard: ^1.0.0
  path_provider: ^2.0.1
  permission_handler: ^6.1.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  firebase_storage: ^8.0.0
  mobx_codegen: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/img/
